services:
    db:
        image: mongo:latest
        container_name: pinstack-mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongo
            - MONGO_INITDB_ROOT_PASSWORD=password
            - MONGO_INITDB_DATABASE=pinstack
        ports:
            - "27017:27017"

    cache:
        image: redis/redis-stack:latest
        container_name: pinstack-redis
        environment:
            - REDIS_ARGS=--requirepass password
        ports:
            - "6379:6379"
            - "8001:8001"

    app:
        build: .
        container_name: pinstack-app
        depends_on:
            - db
            - cache
        ports:
            - "8080:8080"
        env_file:
            - .env
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://mongo:password@db:27017/pinstack?authSource=admin
            - SPRING_DATA_REDIS_HOST=cache
            - SPRING_DATA_REDIS_PORT=6379
            - SPRING_DATA_REDIS_PASSWORD=password

    nginx:
        image: nginx:latest
        container_name: pinstack-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
