spring.application.name=api

spring.mongodb.uri=mongodb://mongo:password@localhost:27017/pinstack?authSource=admin

spring.config.import=optional:file:.env[.properties]
api.security.token.secret=${TOKEN_SECURITY}
app.cors.allowed-origins=${DOMAINS_URL}

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=password

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
