spring.application.name=api

spring.mongodb.uri=mongodb://mongo:password@localhost:27017/pinstack?authSource=admin

spring.config.import=optional:file:.env[.properties]
api.security.token.secret=${TOKEN_SECURITY}
app.cors.allowed-origins=${DOMAINS_URL}

spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=password